name: CI Pipeline

on: [push, pull_request]

jobs:
  code-style:
    runs-on: self-hosted
    name: Code style check
    steps:
    - uses: actions/checkout@v4
    - run: |
        cd src/cat && make clang_n || exit 1
        cd ../grep && make clang_n || exit 1
    - uses: Forkion/C2_SimpleBashUtils/.github/actions/telegram-notify@develop
      if: always()
      with:
        job_name: code_style
        job_status: ${{ job.status }}

  build-cat:
    runs-on: self-hosted
    name: Build cat
    needs: code-style
    steps:
    - uses: actions/checkout@v4  # 1 uses
    - run: |
        cd src/cat
        make
    - uses: actions/upload-artifact@v4  # 2 uses
      with:
        name: copy-cat-binary
        path: src/cat/s21_cat
        retention-days: 1
    - uses: Forkion/C2_SimpleBashUtils/.github/actions/telegram-notify@develop  # 3 uses
      if: always()
      with:
        job_name: build-cat
        job_status: ${{ job.status }}

  build-grep:
    runs-on: self-hosted
    name: Build grep
    needs: code-style
    steps:
    - uses: actions/checkout@v4 # 1 uses
    - run: |
        cd src/grep
        make
    - uses: actions/upload-artifact@v4  # 2 uses
      with:
        name: copy-grep-binary
        path: src/grep/s21_grep
        retention-days: 1
    - uses: Forkion/C2_SimpleBashUtils/.github/actions/telegram-notify@develop  # 3 uses
      if: always()
      with:
        job_name: build-grep
        job_status: ${{ job.status }}

  test-cat:
    runs-on: self-hosted
    name: Test cat
    needs: build-cat
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: copy-cat-binary
        path: src/cat/
    - run: |
        cd src/cat
        make test || exit 1
    - uses: Forkion/C2_SimpleBashUtils/.github/actions/telegram-notify@develop
      if: always()
      with:
        job_name: test-cat
        job_status: ${{ job.status }}

  test-grep:
    runs-on: self-hosted
    name: Test grep
    needs: build-grep
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: copy-grep-binary
        path: src/grep/
    - run: |
        cd src/grep
        make test || exit 1
    - uses: Forkion/C2_SimpleBashUtils/.github/actions/telegram-notify@develop
      if: always()
      with:
        job_name: test-grep
        job_status: ${{ job.status }}
