name: CI Pipeline

on: [push, pull_request]

jobs:
  code-style:
    runs-on: self-hosted
    name: Code style check
    steps:
    - uses: actions/checkout@v4
    - run: |
        cd src/cat && make clang_n || exit 1
        cd ../grep && make clang_n || exit 1
    - uses: ./.github/actions/telegram-notify
      if: always()
      with:
        job_name: code_style
        job_status: ${{ job.status }}

  build-cat:
    runs-on: self-hosted
    name: Build cat
    needs: code-style
    steps:
    - uses: actions/checkout@v4
    - run: |
        cd src/cat
        mkdir -p build
        make
        cp s21_cat build/s21_cat
    - uses: ./.github/actions/telegram-notify
      if: always()
      with:
        job_name: code_style
        job_status: ${{ job.status }}

  build-grep:
    runs-on: self-hosted
    name: Build grep
    needs: code-style
    steps:
    - uses: actions/checkout@v4
    - run: |
        cd src/grep
        mkdir -p build
        make
        cp s21_grep build/s21_grep
    - uses: ./.github/actions/telegram-notify
      if: always()
      with:
        job_name: code_style
        job_status: ${{ job.status }}

  test-cat:
    runs-on: self-hosted
    name: Test cat
    needs: build-cat
    steps:
    - uses: actions/checkout@v4
    - run: |
        cd src/cat
        make test || exit 1
    - uses: ./.github/actions/telegram-notify
      if: always()
      with:
        job_name: code_style
        job_status: ${{ job.status }}

  test-grep:
    runs-on: self-hosted
    name: Test grep
    needs: build-grep
    steps:
    - uses: actions/checkout@v4
    - run: |
        cd src/grep
        make test || exit 1
    - uses: ./.github/actions/telegram-notify
      if: always()
      with:
        job_name: code_style
        job_status: ${{ job.status }}
